BlogTree:
  extensions:
    - BlogCategoryTree

BlogTree_Controller:
  extensions:
    - BlogCategoryTreeExtension_Controller

BlogEntry:
  extensions:
    - BlogCategoryEntry

BlogCategory:
  limit_to_holder: true